apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker
spec:
  acceptors:
  - bindToAllInterfaces: true
    expose: true
    name: acceptor
    sslEnabled: false
  adminPassword: admin
  adminUser: admin
  console:
    expose: true
  deploymentPlan:
    # TODO: Add resource requests / limits
    clustered: true
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: false
    persistenceEnabled: true
    requireLogin: false
    size: 3
    storage:
      size: 5Gi
      storageClassName: truenas
